name: zoco
description: "A new Flutter project."
publish_to: "none"
version: 1.0.14+14

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  go_router: ^13.0.1
  provider: ^6.1.1
  intl_phone_field: ^3.2.0
  otp_text_field: ^1.1.3
  persistent_bottom_nav_bar: ^5.0.2
  video_player: ^2.8.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  animate_do: ^3.3.3
  easy_stepper: ^0.8.3
  flutter_staggered_grid_view:
  dropdown_button2: ^2.3.9
  ticket_widget: ^1.0.2
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  timeline_tile: ^2.0.0
  chewie: ^1.7.5
  google_sign_in: ^6.2.1
  firebase_core:
  firebase_auth:
  http:
  flutter_spinkit: ^5.2.1
  firebase_messaging:
  timezone: ^0.9.2
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.1.2
  firebase_crashlytics:
  firebase_analytics:
  flutter_stripe:
  webview_flutter:
  intl:
  flutter_facebook_auth: ^6.2.0
  location: ^6.0.1
  geocoding: ^2.0.0
  geolocator: ^11.0.0
  readmore: ^3.0.0
  share_plus:
  flutter_rating_bar: ^4.0.1
  http_parser: ^4.0.2
  fluttertoast:
  pinput: ^4.0.0
  dio: ^5.4.3+1
  package_info_plus: ^8.0.0

  hive_flutter:
  permission_handler: ^11.3.1

dev_dependencies:
  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400

        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500

        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800

