// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC1s7-1jGpNUAPvykNiYYor0_Yr0ZAhi4',
    appId: '1:335822083710:android:90461979dfd3cc34daaa2f',
    messagingSenderId: '335822083710',
    projectId: 'ecommerce-32d01',
    storageBucket: 'ecommerce-32d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8dEGhYzUMlSk6quBUlCGHb9ZcUdBsYqY',
    appId: '1:335822083710:ios:df7b643ea208383fdaaa2f',
    messagingSenderId: '335822083710',
    projectId: 'ecommerce-32d01',
    storageBucket: 'ecommerce-32d01.appspot.com',
    androidClientId: '335822083710-0a4iahn17bp0qm4bgg60rvengc7mu25a.apps.googleusercontent.com',
    iosClientId: '335822083710-20m2p55vtrs326h0cgu4m5l4g8tdeq8i.apps.googleusercontent.com',
    iosBundleId: 'app.zoco.owpmf',
  );

}